# Generated by Django 2.2.4 on 2021-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_diseñador',
            field=models.BooleanField(default=False),
        ),
    ]
