# Generated by Django 2.2.4 on 2021-11-11 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearGrupotarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Grupo_tarea', models.CharField(max_length=30)),
                ('fecha_entrega', models.DateField()),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('pendiente', models.BooleanField(null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea1', to='tarea.Creartarea')),
                ('tarea2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea2', to='tarea.Creartarea')),
                ('tarea3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea3', to='tarea.Creartarea')),
            ],
            options={
                'verbose_name': 'Crear grupo tarea',
                'verbose_name_plural': 'Crear grupo tareas',
            },
        ),
    ]
