# Generated by Django 2.2.4 on 2021-11-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_creargrupotarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='rechazarTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=100, null=True)),
                ('Tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarea.Creartarea')),
            ],
        ),
    ]
