# Generated by Django 2.2.4 on 2021-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_rechazartarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creargrupotarea',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creartarea',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
